// src/app/layout.tsx
import type { Metadata } from "next";
import "@/database/firebase.config";
import "@/ui/global.scss";
import { ThemeProvider } from "@/ui/theme/ThemeProvider";
import ThemeToggle from "@/ui/theme/ThemeToggle";
import { themeInitScript } from "@/ui/theme/init-script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    // suppressHydrationWarning: the init script sets data-theme on this
    // element before React hydrates, so the client attributes will not
    // match the server HTML. Scoped to <html> only — it does not
    // suppress warnings for any descendant.
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: static
          // build-time string, no user input; must be synchronous and
          // inline to run before first paint.
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
        />
      </head>
      <body>
        <ThemeProvider>
          <ThemeToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}